### ISSUE TITLE
각 기능에 대한 코드 리팩토링 필요

### ISSUE THREAD

**Issue by alaneelee** [lemonair-improve/lemonair-service#1]
무분별한 flatMap의 사용으로 가독성 측면에서 좋지 않거나 비효율적으로 동작하는 부분이 가장 많은 서버로 개선이 필요합니다.

**Comment by alaneelee** [comment]
완료하였습니다.

**Comment by BYEONGRYEOL** [comment]
커밋 메세지 이슈 태깅 좀 더 신경쓰겠습니다...
