### ISSUE TITLE
CPU, I/O 작업에 대한 스케쥴링 최적화가 필요합니다.

### ISSUE THREAD

**Issue by alaneelee** [lemonair-improve/lemonair-service#3]
각 작업에 대해 어떤 리소스를 주로 사용하는지 파악하고 이를 최적화 하기 위해 paralell, boundedElastic 등의
스케쥴링 작업이 필요합니다.

**Comment by alaneelee** [comment]
완료하였습니다.

**Comment by BYEONGRYEOL** [comment]
제일 신경 쓰였던 부분인데 속이 다 시원합니당
